import { createClient } from "@libsql/client";
import { readFileSync } from "node:fs";
import { chromium } from "/home/mike/.npm/_npx/5e2e484947874241/node_modules/playwright/index.mjs";
const BASE = "http://localhost:3000";
const db = createClient({ url: process.env.TURSO_DATABASE_URL, authToken: process.env.TURSO_AUTH_TOKEN });
const q1 = (sql, args = []) => db.execute({ sql, args }).then((r) => r.rows[0]);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const log = (...a) => console.log(...a);
const gameId = Number((await db.execute("INSERT INTO live_games (title, created_by) VALUES ('Prueba UX en vivo', 1)")).lastInsertRowid);
const qid = Number((await db.execute({ sql: "INSERT INTO live_questions (game_id, position, type, prompt, time_limit) VALUES (?, 1, 'quiz', 'Pregunta 1', 60)", args: [gameId] })).lastInsertRowid);
for (const [i, t] of ["Sí", "No"].entries()) await db.execute({ sql: "INSERT INTO live_options (question_id, position, text, is_correct) VALUES (?, ?, ?, ?)", args: [qid, i + 1, t, i === 0 ? 1 : 0] });
const pin = String(Math.floor(100000 + Math.random() * 900000));
const matchId = Number((await db.execute({ sql: "INSERT INTO live_matches (game_id, host_user_id, company_id, pin) VALUES (?, 1, NULL, ?)", args: [gameId, pin] })).lastInsertRowid);
const browser = await chromium.launch();
try {
  const player = await browser.newContext({ viewport: { width: 390, height: 800 } });
  await player.request.post(`${BASE}/api/live/join`, { headers: { origin: BASE }, data: { pin, nickname: "Tester", acceptedPolicy: true } });
  const pp = await player.newPage();
  await pp.goto(`${BASE}/jugar`);
  const host = await browser.newContext({ storageState: JSON.parse(readFileSync(".claude-tmp/lab/auth.json", "utf8")), viewport: { width: 1280, height: 800 } });
  await host.request.post(`${BASE}/api/live/host/${matchId}/command`, { headers: { origin: BASE }, data: { command: "start" } });
  const ap = await host.newPage();
  await ap.goto(`${BASE}/admin/vivo/${matchId}`, { waitUntil: "networkidle" });
  await sleep(3000);
  await ap.getByRole("button", { name: /jugadores/ }).click();
  await ap.getByRole("dialog").getByRole("button", { name: "Tester" }).click();
  await ap.screenshot({ path: "/tmp/live3-kick.png" });
  await ap.getByRole("dialog").getByRole("button", { name: "¿Sacar a Tester?" }).click();
  await sleep(2500);
  log("expulsado:", (await q1("SELECT kicked_at IS NOT NULL k FROM live_players WHERE match_id = ?", [matchId])).k);
  log("panel:", (await ap.getByRole("dialog").innerText()).replace(/\s+/g, " "));
  log("celular:", (await pp.locator("body").innerText()).replace(/\s+/g, " ").slice(0, 100));
  await ap.keyboard.press("Escape");
  log("panel tras Escape:", await ap.getByRole("dialog").count());
} finally {
  await browser.close();
  await db.execute({ sql: "DELETE FROM live_matches WHERE id = ?", args: [matchId] });
  await db.execute({ sql: "DELETE FROM live_games WHERE id = ?", args: [gameId] });
  log("limpieza hecha");
}
